name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Signing Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_KEY_PASSWORD }}
          fingerprint: ${{ secrets.SIGNING_KEY_ID }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Copy Maven Upload URL
        id: extract_maven_upload_url
        run: echo "maven_upload_url=${{ secrets.MAVEN_UPLOAD_URL }}" >> $GITHUB_OUTPUT
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assemble
        env:
          TAG: ${{ github.ref_name }}
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
          MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
          GPG_SIGNING: true
      - name: Maven Release
        if: steps.extract_maven_upload_url.outputs.maven_upload_url
        run: ./gradlew publish
        env:
          TAG: ${{ github.ref_name }}
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
          MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
          GPG_SIGNING: true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.current-time.outputs.formattedTime }}-build.${{ github.run_number }}
          path: |
            build/libs/*.jar
            build/libs/*.pom
            build/libs/*.module
            build/libs/*.asc
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ github.token }}
